### ISSUE TITLE
C++ test doesn't build in libint 2.6.0

### ISSUE THREAD

**Issue by susilehtola** [evaleev/libint#187]
Enabling Boost and Eigen3 support, building the C++ test program fails with
```
CXX test.o
In file included from /usr/include/boost/preprocessor/detail/auto_rec.hpp:21,
                 from /usr/include/boost/preprocessor/control/while.hpp:20,
                 from /usr/include/boost/preprocessor/arithmetic/add.hpp:20,
                 from /usr/include/boost/preprocessor/arithmetic.hpp:17,
                 from /usr/include/boost/preprocessor/library.hpp:16,
                 from /usr/include/boost/preprocessor.hpp:17,
                 from ../include/libint2/./engine.impl.h:35,
                 from ../include/libint2/engine.h:988,
                 from ../include/libint2/cxxapi.h:41,
                 from ../include/libint2.hpp:24,
                 from test.cc:24:
../include/libint2/./engine.impl.h: In member function 'void libint2::Engine::_initialize()':
../include/libint2/./engine.impl.h:627:3: error: 'LIBINT2_MAX_AM_default1' was not declared in this scope; did you mean 'LIBINT2_MAX_AM_default'?
  627 |   BOOST_PP_LIST_FOR_EACH_PRODUCT(
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/libint2/./engine.impl.h:627:3: error: 'LIBINT2_MAX_AM_default2' was not declared in this scope; did you mean 'LIBINT2_MAX_AM_default'?
  627 |   BOOST_PP_LIST_FOR_EACH_PRODUCT(
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/libint2/./engine.impl.h:627:3: error: 'LIBINT2_MAX_AM_default1' was not declared in this scope; did you mean 'LIBINT2_MAX_AM_default'?
  627 |   BOOST_PP_LIST_FOR_EACH_PRODUCT(
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/libint2/./engine.impl.h:627:3: error: 'LIBINT2_MAX_AM_default2' was not declared in this scope; did you mean 'LIBINT2_MAX_AM_default'?
  627 |   BOOST_PP_LIST_FOR_EACH_PRODUCT(
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/libint2/./engine.impl.h:627:3: error: 'LIBINT2_MAX_AM_default1' was not declared in this scope; did you mean 'LIBINT2_MAX_AM_default'?
  627 |   BOOST_PP_LIST_FOR_EACH_PRODUCT(
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/libint2/./engine.impl.h:627:3: error: 'LIBINT2_MAX_AM_default2' was not declared in this scope; did you mean 'LIBINT2_MAX_AM_default'?
  627 |   BOOST_PP_LIST_FOR_EACH_PRODUCT(
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/libint2/./engine.impl.h:627:3: error: 'LIBINT2_MAX_AM_default1' was not declared in this scope; did you mean 'LIBINT2_MAX_AM_default'?
  627 |   BOOST_PP_LIST_FOR_EACH_PRODUCT(
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/libint2/./engine.impl.h:627:3: error: 'LIBINT2_MAX_AM_default2' was not declared in this scope; did you mean 'LIBINT2_MAX_AM_default'?
  627 |   BOOST_PP_LIST_FOR_EACH_PRODUCT(
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/libint2/./engine.impl.h:627:3: error: 'LIBINT2_MAX_AM_default1' was not declared in this scope; did you mean 'LIBINT2_MAX_AM_default'?
  627 |   BOOST_PP_LIST_FOR_EACH_PRODUCT(
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/libint2/./engine.impl.h:627:3: error: 'LIBINT2_MAX_AM_default2' was not declared in this scope; did you mean 'LIBINT2_MAX_AM_default'?
  627 |   BOOST_PP_LIST_FOR_EACH_PRODUCT(
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/libint2/./engine.impl.h:627:3: error: 'LIBINT2_MAX_AM_default1' was not declared in this scope; did you mean 'LIBINT2_MAX_AM_default'?
  627 |   BOOST_PP_LIST_FOR_EACH_PRODUCT(
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/libint2/./engine.impl.h:627:3: error: 'LIBINT2_MAX_AM_default2' was not declared in this scope; did you mean 'LIBINT2_MAX_AM_default'?
  627 |   BOOST_PP_LIST_FOR_EACH_PRODUCT(
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/libint2/./engine.impl.h:627:3: error: 'LIBINT2_MAX_AM_default1' was not declared in this scope; did you mean 'LIBINT2_MAX_AM_default'?
  627 |   BOOST_PP_LIST_FOR_EACH_PRODUCT(
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/libint2/./engine.impl.h:627:3: error: 'LIBINT2_MAX_AM_default2' was not declared in this scope; did you mean 'LIBINT2_MAX_AM_default'?
  627 |   BOOST_PP_LIST_FOR_EACH_PRODUCT(
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/libint2/./engine.impl.h:627:3: error: 'LIBINT2_MAX_AM_default1' was not declared in this scope; did you mean 'LIBINT2_MAX_AM_default'?
  627 |   BOOST_PP_LIST_FOR_EACH_PRODUCT(
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/libint2/./engine.impl.h:627:3: error: 'LIBINT2_MAX_AM_default2' was not declared in this scope; did you mean 'LIBINT2_MAX_AM_default'?
  627 |   BOOST_PP_LIST_FOR_EACH_PRODUCT(
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/libint2/./engine.impl.h:627:3: error: 'LIBINT2_MAX_AM_default1' was not declared in this scope; did you mean 'LIBINT2_MAX_AM_default'?
  627 |   BOOST_PP_LIST_FOR_EACH_PRODUCT(
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/libint2/./engine.impl.h:627:3: error: 'LIBINT2_MAX_AM_default2' was not declared in this scope; did you mean 'LIBINT2_MAX_AM_default'?
  627 |   BOOST_PP_LIST_FOR_EACH_PRODUCT(
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/libint2/./engine.impl.h:627:3: error: 'LIBINT2_MAX_AM_default1' was not declared in this scope; did you mean 'LIBINT2_MAX_AM_default'?
  627 |   BOOST_PP_LIST_FOR_EACH_PRODUCT(
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/libint2/./engine.impl.h:627:3: error: 'LIBINT2_MAX_AM_default2' was not declared in this scope; did you mean 'LIBINT2_MAX_AM_default'?
  627 |   BOOST_PP_LIST_FOR_EACH_PRODUCT(
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by evaleev** [comment]
seems to be duplicate of #192
