### ISSUE TITLE
Error during installation...

### ISSUE THREAD

**Issue by Physfock** [evaleev/libint#341]
There is an error during installation in Fedora 40

In file included from /usr/include/boost/preprocessor/arithmetic/add.hpp:59,
                 from /usr/include/boost/preprocessor/arithmetic.hpp:17,
                 from /usr/include/boost/preprocessor/library.hpp:16,
                 from /usr/include/boost/preprocessor.hpp:17,
                 from /usr/include/libint2/engine.impl.h:35,
                 from /usr/include/libint2/engine.h:988,
                 from /usr/include/libint2/cxxapi.h:41,
                 from /usr/include/libint2.hpp:24,
                 from Libint2Iface.h:14,
                 from Libint2Iface.cpp:10:
/usr/include/libint2/engine.impl.h: In member function «void libint2::Engine::_initialize()»:
/usr/include/libint2/engine.impl.h:627:3: ошибка: «LIBINT2_MAX_AM_default1» was not declared in this scope; did you mean «LIBINT2_MAX_AM_default»?
  627 |   BOOST_PP_LIST_FOR_EACH_PRODUCT(
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/libint2/engine.impl.h:627:3: ошибка: «LIBINT2_MAX_AM_default2» was not declared in this scope; did you mean «LIBINT2_MAX_AM_default»?
  627 |   BOOST_PP_LIST_FOR_EACH_PRODUCT(
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/libint2/engine.impl.h:627:3: ошибка: «LIBINT2_MAX_AM_default1» was not declared in this scope; did you mean «LIBINT2_MAX_AM_default»?
  627 |   BOOST_PP_LIST_FOR_EACH_PRODUCT(
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/libint2/engine.impl.h:627:3: ошибка: «LIBINT2_MAX_AM_default2» was not declared in this scope; did you mean «LIBINT2_MAX_AM_default»?
  627 |   BOOST_PP_LIST_FOR_EACH_PRODUCT(
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/libint2/engine.impl.h:627:3: ошибка: «LIBINT2_MAX_AM_default1» was not declared in this scope; did you mean «LIBINT2_MAX_AM_default»?
  627 |   BOOST_PP_LIST_FOR_EACH_PRODUCT(
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/libint2/engine.impl.h:627:3: ошибка: «LIBINT2_MAX_AM_default2» was not declared in this scope; did you mean «LIBINT2_MAX_AM_default»?
  627 |   BOOST_PP_LIST_FOR_EACH_PRODUCT(
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/libint2/engine.impl.h:627:3: ошибка: «LIBINT2_MAX_AM_default1» was not declared in this scope; did you mean «LIBINT2_MAX_AM_default»?
  627 |   BOOST_PP_LIST_FOR_EACH_PRODUCT(
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/libint2/engine.impl.h:627:3: ошибка: «LIBINT2_MAX_AM_default2» was not declared in this scope; did you mean «LIBINT2_MAX_AM_default»?
  627 |   BOOST_PP_LIST_FOR_EACH_PRODUCT(
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/libint2/engine.impl.h:627:3: ошибка: «LIBINT2_MAX_AM_default1» was not declared in this scope; did you mean «LIBINT2_MAX_AM_default»?
  627 |   BOOST_PP_LIST_FOR_EACH_PRODUCT(
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/libint2/engine.impl.h:627:3: ошибка: «LIBINT2_MAX_AM_default2» was not declared in this scope; did you mean «LIBINT2_MAX_AM_default»?
  627 |   BOOST_PP_LIST_FOR_EACH_PRODUCT(
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/libint2/engine.impl.h:627:3: ошибка: «LIBINT2_MAX_AM_default1» was not declared in this scope; did you mean «LIBINT2_MAX_AM_default»?
  627 |   BOOST_PP_LIST_FOR_EACH_PRODUCT(
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/libint2/engine.impl.h:627:3: ошибка: «LIBINT2_MAX_AM_default2» was not declared in this scope; did you mean «LIBINT2_MAX_AM_default»?
  627 |   BOOST_PP_LIST_FOR_EACH_PRODUCT(
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/libint2/engine.impl.h:627:3: ошибка: «LIBINT2_MAX_AM_default1» was not declared in this scope; did you mean «LIBINT2_MAX_AM_default»?
  627 |   BOOST_PP_LIST_FOR_EACH_PRODUCT(
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/libint2/engine.impl.h:627:3: ошибка: «LIBINT2_MAX_AM_default2» was not declared in this scope; did you mean «LIBINT2_MAX_AM_default»?
  627 |   BOOST_PP_LIST_FOR_EACH_PRODUCT(
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/libint2/engine.impl.h:627:3: ошибка: «LIBINT2_MAX_AM_default1» was not declared in this scope; did you mean «LIBINT2_MAX_AM_default»?
  627 |   BOOST_PP_LIST_FOR_EACH_PRODUCT(
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/libint2/engine.impl.h:627:3: ошибка: «LIBINT2_MAX_AM_default2» was not declared in this scope; did you mean «LIBINT2_MAX_AM_default»?
  627 |   BOOST_PP_LIST_FOR_EACH_PRODUCT(
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/libint2/engine.impl.h:627:3: ошибка: «LIBINT2_MAX_AM_default1» was not declared in this scope; did you mean «LIBINT2_MAX_AM_default»?
  627 |   BOOST_PP_LIST_FOR_EACH_PRODUCT(
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/libint2/engine.impl.h:627:3: ошибка: «LIBINT2_MAX_AM_default2» was not declared in this scope; did you mean «LIBINT2_MAX_AM_default»?
  627 |   BOOST_PP_LIST_FOR_EACH_PRODUCT(
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/libint2/engine.impl.h:627:3: ошибка: «LIBINT2_MAX_AM_default1» was not declared in this scope; did you mean «LIBINT2_MAX_AM_default»?
  627 |   BOOST_PP_LIST_FOR_EACH_PRODUCT(
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/libint2/engine.impl.h:627:3: ошибка: «LIBINT2_MAX_AM_default2» was not declared in this scope; did you mean «LIBINT2_MAX_AM_default»?
  627 |   BOOST_PP_LIST_FOR_EACH_PRODUCT(
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/libint2/util/generated/libint2_iface.h:26,
                 from /usr/include/libint2.h:43,
                 from /usr/include/libint2/cxxapi.h:29:
Libint2Iface.cpp: In function «void libintinterface_buildg12_(int*, int*, int*, int*, int*, int*, lowdin_t*, double*)»:
Libint2Iface.cpp:3822:25: ошибка: «libint2_init_r12kg12» was not declared in this scope; did you mean «libint2_init_2eri2»?
 3822 |   LIBINT2_PREFIXED_NAME(libint2_init_r12kg12)(&inteval, *max_am, 0);
      |                         ^~~~~~~~~~~~~~~~~~~~
Libint2Iface.cpp:3828:25: ошибка: «libint2_build_r12kg12» was not declared in this scope; did you mean «libint2_build_2eri2»?
 3828 |   LIBINT2_PREFIXED_NAME(libint2_build_r12kg12)[*na][*nb][*nc][*nd](&inteval);
      |                         ^~~~~~~~~~~~~~~~~~~~~

**Comment by evaleev** [comment]
Could you provide more details? (Version, how compiler was configured, whether library was exported and then built separately, or whether it was built within the compiler built, etc) Specially it appears that angular momenta specification is faulty or unsupported.

**Comment by JonathonMisiewicz** [comment]
OP can reopen if they return. Otherwise, closing this.
