### ISSUE TITLE
cmake fail

### ISSUE THREAD

**Issue by nadnatalia** [evaleev/libint#170]
Hi,

I have been trying to compile libint2.6 for cp2k7.1. I always stumble on the second part of cmake. I used spack to compile cp2k (hence libint compilation was also done under spack). Attached is the out and the error log that were given out by spack. 

I have also tried to compile libint using https://xconfigure.readthedocs.io/en/latest/libint/ as a step by step guidance, and every time I invoke the "make distclean" command it spits me out instantaneously with the following error:
```console
make: *** No rule to make target `distclean'.  Stop.
```

Please help?

[error.txt](https://github.com/evaleev/libint/files/4562124/error.txt)
[spack-build-out.txt](https://github.com/evaleev/libint/files/4562129/spack-build-out.txt)

**Comment by evaleev** [comment]
this
```
     2004    In file included from ./include/libint2.h:34:0,
     2005                     from src/CR_aB_X0__0___Overlap_X0__0___Ab__up_.cc:21:
  [0;91m>> 2006    ./include/libint2/util/generated/libint2_params.h:29:22: error: missing binary operator before token "("[0m
     2007     #    if __has_include(<libint2_params.h>)
     2008                          ^
```
suggests that the c++ compiler is not c++11 compliant ... which compiler is being used?

**Comment by nadnatalia** [comment]
I used gcc@4.8.5, which I learned is not c++11 compliant. I am trying to recompile with gcc@8.2.0
